services:
  asciidoctor:
    image: asciidoctor/docker-asciidoctor:1.82
    command: asciidoctor-revealjs -r asciidoctor-diagram index.adoc
    volumes:
      - .:/documents
    working_dir: /documents
    # remove: true
