// == What are dotfiles?
//
// [quote,https://wiki.archlinux.org/title/Dotfiles]
// User-specific application configuration is traditionally
// stored in so called dotfiles (files with filenames starting with a dot).
//
// [.notes]
// ****
// Dotfiles are text files containing the configuration of your software. This can be your git configuration, your SSH hosts. These files are usually stored in your home directory and start with a dot, which explains the dotfiles' name.
//
// Why should you care to back these up ? Because they contain important configuration data, and you don't want to start over everytime you install a new workstation or reconfigure it.
// ****

== What are dotfiles?

[%linenums,shell]
.~/.bashrc
----
#!/usr/bin/env bash

if [ -f /etc/bashrc ]; then
 . /etc/bashrc
fi

export SSH_AUTH_SOCK=/run/user/1000/ssh-agent.socket
# ...
----

> Others : vimrc, gitconfig, ...

[.notes]
****
Dotfiles are text files containing the configuration of your software. This can be your git configuration, your SSH hosts. These files are usually stored in your home directory and start with a dot, which explains the dotfiles' name.

Here you can see an example of `.bashrc` that export a custom environment variable.

You probably have multiple dotfiles on your workstation for your vim configuration or your kubernetes config file.
****

== How to manage them?

https://dotfiles.github.io/

https://github.com/webpro/awesome-dotfiles

[.notes]
****
Now that we've seen what dotfiles are, we'll see how to store them to ensure we can quickly recover them if your workstation suddenly dies.

GitHub has a website where various ways to manage these dotfiles exist, and there is also an awesome-dotfiles repository which lists other ways. Right now we'll see a few options and the one I've chosen.
****
