[.columns.is-vcentered]
== Homemade script

[.column]
--
Shell, Python, C, PHP... The choice is yours, let's code!
--

[.column.language_logo]
--
image::bash-logo.svg[]

image::python-logo.svg[]

--

[.column.language_logo]
--
image::C-logo.svg[]

image::PHP-logo.svg[]
--

[.notes]
****
Let's move on to the next solution. Since the majority of us here are developers, grab your favorite language, a coffee or some tea and build your own tool !
****

=== Pros and Cons

[%autowidth.stretch,cols="1,1"]
|===
|Goal | State
|Manage configuration files
|✅
|Manage installed software
|✅
|Version Control
|✅
|Maintainability
|😐
|Manage personal and pro workstation
|✅
|Can handle secrets
|✅
|===

[.notes]
****
The main advantage is that you can do everything you want, with your favorite language !

You'll be able to check all these requirements and even more. You're the one in charge, from the beginning to the end.

However, how much time will you need to craft this tool to fit every one of your needs ? It can be very time-consuming, and you may spend more time fixing your tool than configuring your laptop. It can be a fun side project though but that is not what I was looking for.
****
