== Stow

[quote,https://www.gnu.org/software/stow/manual/stow.html#Bootstrapping]
GNU Stow is a symlink farm manager which takes distinct sets of software and/or data located in separate directories on the filesystem, and makes them all appear to be installed in a single directory tree.

[.notes]
****
Now let's take a look at a dedicated tool to manage your dotfiles. Stow is a Linux tool that does one thing, and as per the Unix philosophy, it does this thing well.

Stow will take a folder with an arborescence of files, and will replicate it to another directory of your filesystem (your home directory) with symlinks. So this means you can store all your dotfiles in a dedicated directory, version control this folder with Git, and with one command, you'll sync your dotfiles on your workstation!
****

=== Pros and Cons

[%autowidth.stretch,cols="1,1"]
|===
|Goal | State
|Manage configuration files
|✅
|Manage installed software
|❌
|Version Control
|✅
|Maintainability
|✅
|Manage personal and pro workstation
|😐
|Can handle secrets
|❌
|===

[.notes]
****
The advantage is that it is easy to set up and quite easy to maintain, thanks to the symlinks it will create on your filetree.

However, if we take a look at my requirements, we see that I can only manage dotfiles, and I'll have to find another way to manage my installed software. If you have many workstations, you'll have to store the common configuration on a dedicated folder and may need to run multiple commands to sync your dotfiles. Finally, you'll need to use another tool to store your secret, such as age and/or pgp, and encrypt/decrypt your secrets before being able to use these.
****